# Generated by Django 3.2.18 on 2023-05-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='morph',
            name='client_id',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
