# Generated by Django 3.2.18 on 2023-06-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0006_animegan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animegan',
            old_name='animegan_image_ref',
            new_name='uri',
        ),
    ]
