# Generated by Django 3.2.18 on 2023-06-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0007_rename_animegan_image_ref_animegan_uri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animegan',
            old_name='animegan_image_filepath',
            new_name='filepath',
        ),
    ]
