# Generated by Django 4.2.27 on 2026-01-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0009_alter_upload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animegan',
            name='filepath',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='animegan',
            name='image_ref',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='animegan',
            name='uri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='morph',
            name='first_image_ref',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='morph',
            name='morphed_image_filepath',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='morph',
            name='morphed_image_ref',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='morph',
            name='second_image_ref',
            field=models.CharField(max_length=255),
        ),
    ]
