# Generated by Django 4.2.x

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0010_alter_animegan_filepath_alter_animegan_image_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='morph',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
