# Generated by Django 4.2.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morph', '0011_morph_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='morph',
            name='intermediate_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
